# Alembic configuration file
#
# This file is used by Alembic to manage migrations.
#
# For more information, see:
# https://alembic.sqlalchemy.org/en/latest/tutorial.html

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file as well
# as the filename.
# If specified, requires the python-dateutil library.
#
# timezone = UTC

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s

[post_write_hooks]
# post_write_hooks defines scripts or Python functions to run after Alembic
# generates a new migration file. See the documentation for more details.
# hooks =

[alembic:exclude]
# tables = spatial_ref_sys
