"""add guests_count to bookings

Revision ID: 537a6d4fee05
Revises: 6c3cd029f10d
Create Date: 2026-04-20 22:24:37.428020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537a6d4fee05'
down_revision = '6c3cd029f10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guests_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('guests_count')

    # ### end Alembic commands ###
