"""autogenerate models

Revision ID: b5dcf73c210b
Revises: 64917f076cf6
Create Date: 2026-03-06 18:40:39.935666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b5dcf73c210b"
down_revision = "64917f076cf6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraservices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_number", sa.String(length=10), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("price_per_night", sa.Float(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("available", "maintenance", "unavailable", name="roomstatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_number"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("guest", "receptionist", "admin", name="role"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("check_in", sa.DateTime(), nullable=False),
        sa.Column("check_out", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "cancelled",
                "checked_in",
                "checked_out",
                name="bookingstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "booking_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["extraservices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("paid", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_id"),
    )
    op.drop_table("booking")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("email"))
        batch_op.drop_index(batch_op.f("username"))

    op.drop_table("user")
    with op.batch_alter_table("room", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("room_number"))

    op.drop_table("room")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("room_number", mysql.VARCHAR(length=10), nullable=False),
        sa.Column("capacity", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("price_per_night", mysql.FLOAT(), nullable=False),
        sa.Column(
            "is_available",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("room", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("room_number"), ["room_number"], unique=True)

    op.create_table(
        "user",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", mysql.VARCHAR(length=80), nullable=False),
        sa.Column("email", mysql.VARCHAR(length=120), nullable=False),
        sa.Column("role", mysql.VARCHAR(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("username"), ["username"], unique=True)
        batch_op.create_index(batch_op.f("email"), ["email"], unique=True)

    op.create_table(
        "booking",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("room_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("check_in", mysql.DATETIME(), nullable=False),
        sa.Column("check_out", mysql.DATETIME(), nullable=False),
        sa.Column("status", mysql.VARCHAR(length=20), nullable=True),
        sa.ForeignKeyConstraint(["room_id"], ["room.id"], name=op.f("booking_ibfk_1")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("booking_ibfk_2")),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("invoices")
    op.drop_table("booking_services")
    op.drop_table("bookings")
    op.drop_table("users")
    op.drop_table("rooms")
    op.drop_table("extraservices")
    # ### end Alembic commands ###
